# Generated by Django 4.2.4 on 2023-08-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_manager_app', '0002_alter_worker_position'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
    ]
